services:
  - type: web
    name: api-shl-ui
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run api.py --server.port $PORT --server.enableCORS false"
    plan: free
    autoDeploy: true
