services:
  - type: web
    name: streamlit-shl-ui
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run main.py --server.port $PORT --server.enableCORS false"
    plan: free
    autoDeploy: true
